### ISSUE TITLE
Large number of errors with no source code changes

### ISSUE THREAD

**Issue by ghost** [stanriders/hl2-asw-port#1]
I don't know what I'm doing wrong, yet when i compile with Vs 2010 or 2013 i get in excess of 150 errors each time

**Comment by stanriders** [comment]
Are you using Debug or Release mode when compiling?

**Comment by ghost** [comment]
debug

**Comment by stanriders** [comment]
I see. I'm fixing it right now. Project should compile fine on Release, tho

**Comment by ghost** [comment]
on an unrelated note, how easy is implementing existing hl2 sdk weapons?

**Comment by stanriders** [comment]
Should be same as implementing weapons in 2007/2013 hl2 sdk.

Fixed, https://github.com/stanriders/hl2-asw-port/commit/6a95dfcf2e605a3b1a32fefe2c2e77ae7e6f33a2
